### ISSUE TITLE
NPM Post-Install fails with strict mode violation

### ISSUE THREAD

**Issue by pdfowler** [samueleaton/npm-scripts-gui#2]
I'm eager to try this out, but I'm running into an issue with the post-install script on node 12.7. I didn't notice any node version requirements, or other dependencies, so that probably has something to do with it :)

```
> npm-scripts-gui@0.0.7 postinstall /Users/patf/.nvm/versions/node/v0.12.7/lib/node_modules/npm-scripts-gui
> node postInstall.js

/Users/patf/.nvm/versions/node/v0.12.7/lib/node_modules/npm-scripts-gui/postInstall.js:2
const fs = require('fs');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/Users/patf/.nvm/versions/node/v0.12.7/bin/npm" "i" "-g" "npm-scripts-gui"
npm ERR! node v0.12.7
npm ERR! npm  v2.14.11
npm ERR! code ELIFECYCLE

npm ERR! npm-scripts-gui@0.0.7 postinstall: `node postInstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the npm-scripts-gui@0.0.7 postinstall script 'node postInstall.js'.
npm ERR! This is most likely a problem with the npm-scripts-gui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node postInstall.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls npm-scripts-gui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/patf/Outset/Source/npm-debug.log
```

**Comment by samueleaton** [comment]
Thanks for letting me know. the `postInstall.js` file was the only script not part of the babel build step. I added it and then tested on `v0.12.7` and `v0.10.33`. it worked on both of those. 

Fixed in: af1738c9c6353d3577abb2c22b18784875151fee
